/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/DocumentResult`; params?: Router.UnknownInputParams; } | { pathname: `/Dowload`; params?: Router.UnknownInputParams; } | { pathname: `/ShowDocument`; params?: Router.UnknownInputParams; } | { pathname: `/UploadModal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Alerts` | `/Alerts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Search` | `/Search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Upload` | `/Upload`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/Medicines`; params?: Router.UnknownInputParams; } | { pathname: `/document/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/DocumentResult`; params?: Router.UnknownOutputParams; } | { pathname: `/Dowload`; params?: Router.UnknownOutputParams; } | { pathname: `/ShowDocument`; params?: Router.UnknownOutputParams; } | { pathname: `/UploadModal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Alerts` | `/Alerts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Search` | `/Search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Upload` | `/Upload`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Medicines`; params?: Router.UnknownOutputParams; } | { pathname: `/document/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/DocumentResult${`?${string}` | `#${string}` | ''}` | `/Dowload${`?${string}` | `#${string}` | ''}` | `/ShowDocument${`?${string}` | `#${string}` | ''}` | `/UploadModal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Alerts${`?${string}` | `#${string}` | ''}` | `/Alerts${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Profile${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Search${`?${string}` | `#${string}` | ''}` | `/Search${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Upload${`?${string}` | `#${string}` | ''}` | `/Upload${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/Medicines${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/DocumentResult`; params?: Router.UnknownInputParams; } | { pathname: `/Dowload`; params?: Router.UnknownInputParams; } | { pathname: `/ShowDocument`; params?: Router.UnknownInputParams; } | { pathname: `/UploadModal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Alerts` | `/Alerts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Search` | `/Search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Upload` | `/Upload`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/Medicines`; params?: Router.UnknownInputParams; } | `/document/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/document/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
